/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as AppCallbacksGithubAppSetupRouteImport } from './routes/app/callbacks/github-app/setup'
import { Route as AppCallbacksOauthGithubRouteImport } from './routes/app/callbacks/oauth/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallbacksGithubAppSetupRoute =
  AppCallbacksGithubAppSetupRouteImport.update({
    id: '/app/callbacks/github-app/setup',
    path: '/app/callbacks/github-app/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCallbacksOauthGithubRoute = AppCallbacksOauthGithubRouteImport.update({
  id: '/app/callbacks/oauth/github',
  path: '/app/callbacks/oauth/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drafts'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drafts'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  id:
    | '__root__'
    | '/'
    | '/drafts'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftsRoute: typeof DraftsRoute
  AppCallbacksGithubAppSetupRoute: typeof AppCallbacksGithubAppSetupRoute
  AppCallbacksOauthGithubRoute: typeof AppCallbacksOauthGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/github-app/setup': {
      id: '/app/callbacks/github-app/setup'
      path: '/app/callbacks/github-app/setup'
      fullPath: '/app/callbacks/github-app/setup'
      preLoaderRoute: typeof AppCallbacksGithubAppSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/oauth/github': {
      id: '/app/callbacks/oauth/github'
      path: '/app/callbacks/oauth/github'
      fullPath: '/app/callbacks/oauth/github'
      preLoaderRoute: typeof AppCallbacksOauthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftsRoute: DraftsRoute,
  AppCallbacksGithubAppSetupRoute: AppCallbacksGithubAppSetupRoute,
  AppCallbacksOauthGithubRoute: AppCallbacksOauthGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
