/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppCallbacksSlackRouteImport } from './routes/app/callbacks/slack'
import { Route as AppCallbacksGithubAppSetupRouteImport } from './routes/app/callbacks/github-app/setup'
import { Route as AppCallbacksOauthGithubRouteImport } from './routes/app/callbacks/oauth/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/app/inbox',
  path: '/app/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallbacksSlackRoute = AppCallbacksSlackRouteImport.update({
  id: '/app/callbacks/slack',
  path: '/app/callbacks/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallbacksGithubAppSetupRoute =
  AppCallbacksGithubAppSetupRouteImport.update({
    id: '/app/callbacks/github-app/setup',
    path: '/app/callbacks/github-app/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCallbacksOauthGithubRoute = AppCallbacksOauthGithubRouteImport.update({
  id: '/app/callbacks/oauth/github',
  path: '/app/callbacks/oauth/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/': typeof AppIndexRoute
  '/app/callbacks/slack': typeof AppCallbacksSlackRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/inbox': typeof AppInboxRoute
  '/app': typeof AppIndexRoute
  '/app/callbacks/slack': typeof AppCallbacksSlackRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/': typeof AppIndexRoute
  '/app/callbacks/slack': typeof AppCallbacksSlackRoute
  '/app/callbacks/github-app/setup': typeof AppCallbacksGithubAppSetupRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/inbox'
    | '/app/'
    | '/app/callbacks/slack'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/inbox'
    | '/app'
    | '/app/callbacks/slack'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  id:
    | '__root__'
    | '/'
    | '/app/inbox'
    | '/app/'
    | '/app/callbacks/slack'
    | '/app/callbacks/github-app/setup'
    | '/app/callbacks/oauth/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCallbacksSlackRoute: typeof AppCallbacksSlackRoute
  AppCallbacksGithubAppSetupRoute: typeof AppCallbacksGithubAppSetupRoute
  AppCallbacksOauthGithubRoute: typeof AppCallbacksOauthGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/app/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/slack': {
      id: '/app/callbacks/slack'
      path: '/app/callbacks/slack'
      fullPath: '/app/callbacks/slack'
      preLoaderRoute: typeof AppCallbacksSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/github-app/setup': {
      id: '/app/callbacks/github-app/setup'
      path: '/app/callbacks/github-app/setup'
      fullPath: '/app/callbacks/github-app/setup'
      preLoaderRoute: typeof AppCallbacksGithubAppSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/oauth/github': {
      id: '/app/callbacks/oauth/github'
      path: '/app/callbacks/oauth/github'
      fullPath: '/app/callbacks/oauth/github'
      preLoaderRoute: typeof AppCallbacksOauthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppCallbacksSlackRoute: AppCallbacksSlackRoute,
  AppCallbacksGithubAppSetupRoute: AppCallbacksGithubAppSetupRoute,
  AppCallbacksOauthGithubRoute: AppCallbacksOauthGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
